# Generated by Django 4.0 on 2022-06-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landmodel',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
