# Generated by Django 4.0 on 2022-06-04 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landmodel',
            name='thumbnail',
        ),
    ]
