# Generated by Django 4.0.6 on 2022-07-10 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_landmodel_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='landmodel',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
